### ISSUE TITLE
SQL files contain duplicate definitions

### ISSUE THREAD

**Issue by dominicbetts** [Azure-Samples/MyDriving#405]
The file src\SQLDatabase\sql_createtables.txt appears to contain similar table definitions to scripts\SQLDatabase\MyDrivingAnalyticsDB.sql. Should both be in the repository?

**Comment by HaishiBai** [comment]
The DataFactory, HDInsight, SQLDatabase and StreamAnalytics folders contain the captured sources for different parts, while the scripts folder contains the automation scripts. Yes they are the same but in different context.
