### ISSUE TITLE
Prepare the repo for contributions

### ISSUE THREAD

**Issue by nickvdheuvel** [Azure-Samples/MyDriving#486]
- Remove all branches (feature, hotfix, etc.) and keep only dev (which has yet to be created) and master branch. Feature and hotfix branches in pull requests only. This to improve the understandability of the repository structure and make the repository more consistent with other Microsoft repositories.
- Create guidelines how to create a pull request to the dev branch. This to improve the possibilities to contribute to this repo.

The [Office Dev PnP](https://github.com/OfficeDev/PnP) repo is a good example.

**Comment by jamesmontemagno** [comment]
Lovely! We have removed all branches, and created a dev branch. 

Next, we will be creating guidelines for PRs.

**Comment by harikm86** [comment]
At this point, we are not taking any contributions since we are not completely set up to do so.. We might do so in the future, in the meantime closing this issue.
