### ISSUE TITLE
Fail on run powershell: deploy

### ISSUE THREAD

**Issue by KevinKao809** [Azure-Samples/MyDriving#489]
Get error message on powershell: Resource Microsoft.Web/sites/sourcecontrols 'mydriving-ypgf7j2agcno/web' failed with message 'The resource operation completed with terminal provisioning state 'Failed'.'

I think the webapp name (mydriving-.../web) is not a valid name. any sugesstion ?

Kevin Kao

**Comment by HaishiBai** [comment]
Hi KevinKao809, this could be a transient error. The name should be fine. Can you please open the resource group on Azure Portal, open its Deployments history and get the detailed error message there?

**Comment by HaishiBai** [comment]
A fix has just been merged to fix this bug. Please try again.

**Comment by KevinKao809** [comment]
Haishi,
Get these two updated json files and re-deploy, but still get same issue.

Kevin Kao

**Comment by jainr** [comment]
+1

**Comment by f2bo** [comment]
Hi @KevinKao809 / @jainr,

Can you verify if the mobile app's application settings contain a setting named _"Project"_ and that its value is _"src/MobileAppService/MyDrivingService/MyDrivingService.csproj"_. If not, can you delete the mobile app and run the deployment script again. 

If you're still having trouble after redeploying, can you include a detailed error message. You can find it in the Azure portal, under the Deployments blade of the resource group.

Thanks
