### ISSUE TITLE
Device sleep causes app crash on Windows Phone 10

### ISSUE THREAD

**Issue by seiggy** [Azure-Samples/MyDriving#491]
If I start tracking a route and the device locks, the app appears to crash, as once i unlock the device, it just goes to a black screen, and I can't get the app to respond. Device is a Lumia 950 running build 14295. Using a Bluetooth obdii device. Can we add an option to prevent the device from going to sleep when plugged in?

**Comment by VaijanathA** [comment]
Hello seiggy,

The UWP app uses ExtendedExecutionSession which enables to run the app even when it is locked.  Can you please provide us with exact repro steps so that I can replicate this issue successfully?

Thanks,
Vaijanath

**Comment by seiggy** [comment]
Sure, steps I've taken last 3 days that repro this:
Start Car
Ensure Bluetooth connection to OBDII sensor
Start App
Start Trip Recording
Drive commute (~30 miles)
Turn on device and unlock, get non responsive black screen.

Happens for me every time. I'll try again tomorrow with the latest update.

**Comment by VaijanathA** [comment]
Hello Seiggy,

Please install a build later than 394 and let me know if you still hit this issue. The app should not crash whenever it cannot start an Extended Execution session to run the app in background. Thanks for the feedback and the detailed repro steps. 

Thanks,
Vaijanath
