### ISSUE TITLE
Device Debugging on Android failing

### ISSUE THREAD

**Issue by dankraus** [Azure-Samples/MyDriving#500]
Hi, I'm not sure if this is the best place to raise this as I'm not entirely sure if it's a problem with the App, Visual Studio, or my phone itself.

I had a lot of issues getting the Android version to debug on my Samsung S7. 

> The application could not be started. Ensure that the application has been installed to the target device and has a launchable activity (MainLauncher = true).
> 
> Additionally, check Build->Configuration Manager to ensure this project is set to Deploy for this configuration.

It was definitely set to Deploy. Finally, editing the Android Options for the project and checking off `Use Fast Deployment` would get it working. Unchecking `Use Shared Runtime` would also work but leaving `Use Shared Runtime` online would not.

**Comment by jamesmontemagno** [comment]
It depends on some of the devices and usually works alright with that option turned on. Working good on my 6P. I will ask the team if anyone has one sitting around. I assume emulator isnjust fine though?

Is it the 7 or 7 edge?

**Comment by dankraus** [comment]
Thanks, James. 

It's the regular 7. 

I'm giving Visual Studio for the first time with Xamarin and hadn't given the emulator a whirl as I hadn't set it up yet. Ive always worked with Xamarin Studio on OSX. I had tried with the default ones but it didn't seem to be starting up. Admittedly I ran out of patience. The emulator was always such a bear compared to the iOS one so I generally debugged on my Android device directly.

**Comment by nicolehaugen79** [comment]
Hi dankraus-

I recently have seen a similar issue when debugging the MyDriving app to an Android emulator.
Could you tell us what version of VS you are using - have you updated to VS 2015 Update 2?  Also, what version of the Android SDK and Tools you have installed.  You can check this through the Android SDK a Manager which can be opened via the toolbar next to the debugger drop down in VS.

Last but not least, could you try a few things to see if this solves the problem?

1.) Create a new, blank Xamarin Android project in Visual Studio - specifically, in the New Project window, select the Cross-Platform -> Blank App (Native Portable) project template which will create a native Xamarin app that contains Android\iOS\Winphone projects.  Debug this app using your device to see if it deploys successfully.  If it does, try switching back the MyDriving app and try again to debug it using your device.

2.) Update the newest version of the Android SDK and Tools using the Android SDK manager that I mentioned earlier. 

Let us know if this helps.

Thanks,
Nicole

**Comment by dankraus** [comment]
Hi @nicolehaugen79,

I'm running VS Community 2015 Update 2. I have Android SDK Tools 25.1.1 (latest as of right now), Android SDK Platform-tools 23.1, Android SDK Build-tools 23.0.1 and 21.1.2

The Blank project debugged to my phone with `Use Shared Runtime` checked and both with and without `Use Fast Deployment` checked as well.

I switched back to MyDriving and with `Use Shared Runtime` checked and `Use Fast Deployment` unchecked (which was the default when I first spun all this up), it debugged and worked.

So.... No idea what the heck was going on then.. :question:

After trying this out, i installed Android SDK Build-tools 23.0.3 (latest as of right now) for good measure.

Thanks for paying attention to this. I was so excited to see an in-depth free ebook like this. Between that and the response here, it keeps my hopes high about the continuing future of Xamarin! I'm very excited to go to Evolve next week!

**Comment by nicolehaugen79** [comment]
Glad that you now have it working - I'm still trying to understand the root issue, but have noticed that if you deploy a blank Android app and then switch back to MyDriving and deploy, that it then deploys successfully.  I appreciate your response because this helps to confirm that you are seeing the same behavior that I also noticed.

It's great to hear your excitement - have a great Evolve next week!

**Comment by nicolehaugen79** [comment]
We have a workaround which is to deploy a clean, Xamarin Android app...followed by re-deploying the MyDriving app which then solves the issue.  As a result, I'm closing this issue.
