### ISSUE TITLE
[UWP]Prevent app from navigating to previous screen using back button when recording in Current trip

### ISSUE THREAD

**Issue by VaijanathA** [Azure-Samples/MyDriving#501]
When we recording a trip, pressing back hardware button takes it to Login screen and all the recording information is lost.  We should prevent app from navigating to previous screen when we use a back button.

**Comment by PiDiBi** [comment]
try to put in TryGoBack something like
if (Frame.BackStack.First().IsTypeOf(typeof(LoginView))) return navigated;

**Comment by VaijanathA** [comment]
@PiDiBi Its a nice suggestion.  I changed it to not go back when we are recording. This was causing issues and I fixed it this way.
