### ISSUE TITLE
Can't Download Past Trips (UWP)

### ISSUE THREAD

**Issue by elwardrm** [Azure-Samples/MyDriving#502]
I can record trips (using an paired OBD) and when finished and I stop the recording I get a the screen that says it is saving the trip.  The trip shows up in the past trips list but when I try to retrieve one it says Unable to load Trip...Please check internet connection and try again.  I'm connected to the internet because I can browse with IE.

Nokia 635 phone running Windows 10 Mobile (10.0.10586.107 OS).

**Comment by VaijanathA** [comment]
Hello elwardrm,

Thanks for reporting this issue. Do you see the same issue when you restart the app ? This might also happen due to a weak/faulty network connection as the error says it is unable to find the network. Please let us know if you see this issue even after restart or joining a WIFI network. 

Thanks,
VJ

**Comment by elwardrm** [comment]
VJ,
I rebooted the phone to be sure the application was reloaded.  I also made sure I was under a Wi-Fi access point with as strong Wi-Fi signal.  Still tunable to load the past trips from today.  The interesting thing is that this has been flaky all week.  I have three trips from 2 and 3 days ago that I can load the past trip.  But those trips would have been with an earlier version as I am trying to load each new release to see if it fixes the problem.
Thanks,
Bob

-----------------------------------------------------------------------
Bob Elward, P.E. | Director, IT Materials Technologies Separation
Air Products & Chemicals Inc. | 7201 Hamilton Blvd. | Allentown, PA 18195
elwardrm@airproducts.com<mailto:elwardrm@airproducts.com> | •610-481-6644
-----------------------------------------------------------------------
This communication is intended solely for the person addressed and is confidential and may be privileged. If you receive this communication incorrectly, please return it immediately to the sender and destroy all copies in your files. If you have questions, please contact the sender of this message.

**Comment by elwardrm** [comment]
VJ,
I was able to get a trip saved and then retrieve it as a post trip.  Aging this seems to be very hit and miss.  I'm pretty sure it's not my network connection as I check each time to see if I can browse the web with IE.

Additionally, the "profile" page shows the summary of all my trips but doesn't score my driving skills.  All I get is 0%.

Thanks,
Bob

**Comment by dankraus** [comment]
Android -- I wasn't able to view an individual Past Trip when I tried on April 14 and April 15. This morning it pulls up fine though. On WiFi now and the previous times I was not but had strong signal. I would tap the trip and it would flash a loading dialog and immediately go back to the Past Trips screen.

Now that I can actually see Past Trips for the first time, it's pretty nifty to slide through the trip! Cool!

**Comment by VaijanathA** [comment]
Hello Elwardrm/Dankraus,

We are tracking this as #508 I will go ahead and close this. Thanks for reporting these issues. 

~VaijanathA
