### ISSUE TITLE
cannot import ML experiment

### ISSUE THREAD

**Issue by PiDiBi** [Azure-Samples/MyDriving#506]
hi, import ends with 
Invoke-RestMethod : AuthenticationFailedA security token exception occured for the received JWT token.
At C:\Users\dabures\Desktop\Projects\MyDriving\scripts\PowerShell\scripts\copyMLExperiment.ps1:33 char:16
+ ...      $res = Invoke-RestMethod -Uri $URI -Method $method -Headers $hea ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

I'v tried both: thumbprint and AAD

Is there another way, how to create ML experiment? step by step tutorial or some way how to fix it?
thx

**Comment by happyjem** [comment]
I can not solve this problem about thumbprint and AAD
I want to more detail step by step tutorial or some way.

**Comment by happyjem** [comment]
I've solved the problem. The key to making the correct certificate file to upload. Please refer here.
"http://nightskyhunter.tistory.com/12" Although Korean, but it would be helpful to create and upload the certificate. And copy and paste thumbprint after uploading "unpack". The characters that would appear to continue. Then Deploy the VSTS CI to happen. Maybe this was going to be easy. It is preferable to install the machine learnning hard than I thought. Next time, ask for a more detailed description. Please note that this article is using bing translator, grammar or vocabulary may not fit. Please be aware, thank you.

**Comment by PiDiBi** [comment]
I tried to use certificate, but it ends with this error:
Invoke-RestMethod : Unable to retrieve certificates because the thumbprint is not valid. Verify the thumbprint and retry. 
I created and uploaded certificate and thumbprint is correct, checked more times

**Comment by PiDiBi** [comment]
there was hidden utf-8 character in thumbrint :(
I solved it by passing parameter this way
[string]$thumbprint = "...."

for others, this way works:
makecert -sky exchange -r -n "CN=db1" -pe -a sha1 -len 2048 -ss My db1.cer
go to https://manage.windowsazure.com/ - Settings - Management Certificates and upload certificate
copy thumbprint and use for importing ML experiments

@happyjem thx
