### ISSUE TITLE
Stopping a trip takes a very long time

### ISSUE THREAD

**Issue by elwardrm** [Azure-Samples/MyDriving#507]
When I record a trip and press the stop button nothing seems to happen.  I press the button multiple times and nothing appears to happen.  It seems to take 30-60 seconds for the trip to stop recording and to get the prompt to name the trip before it saves it (Uploads it to the cloud?).

Seems that there should be immediate feedback that the "stop trip" request was acknowledged.

**Comment by VaijanathA** [comment]
@elwardrm . When you stop the trip, the stop button gets disabled and you should see a "Saving Trip ..."  dialog. The mobile app service tries to upload all the trip points that were not uploaded at the end. This causes the delay. Please let us know if you do not see this "Saving Trip..." dialog at the top.

**Comment by VaijanathA** [comment]
@elwardrm I changed the Stop button to reflect immidiately once user presses it so that they have visible feedback once pressed. Thanks for the feedback. I will close this issue now.
