### ISSUE TITLE
Profile page is inaccurate

### ISSUE THREAD

**Issue by elwardrm** [Azure-Samples/MyDriving#509]
My Profile page doesn't seem to summarize all the trip I take.  It also doesn't show my Driving skills percentage.

**Comment by harikm86** [comment]
Are you using an iPhone, Android or Windows device? Also, do you have a OBD device plugged into the car?

**Comment by elwardrm** [comment]
Using a Windows phone (Nokia 635) and a BAFX 34t5 Bluetooth OBDII

**Comment by alinapopa** [comment]
@elwardrm There was issue on our end that "Driving skills" was not coming in. It is fixed now, you can see the percentage updates if you make a trip with the OBD device connected.
Relating to this part "My Profile page doesn't seem to summarize all the trip I take", please can you provide more details, what is missing?

**Comment by alinapopa** [comment]
Closing since this was fixed. Please reopen if you still observe issues.
