### ISSUE TITLE
cannot connect to OBD if connected to Bluetooth handsfree

### ISSUE THREAD

**Issue by PiDiBi** [Azure-Samples/MyDriving#510]
UWP app at 950XL
I'm unable to use myDriving together with BT HF - it disconnects short after connection
No idea if it's OBD driver implementation issue or BT stack issue

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.
Can you give more information about "it disconnects short after connection"? 
Did you see this in settings->bluetooth?

**Comment by PiDiBi** [comment]
yes
I'ts paired, I click on dongle name in settings->bluetooth, it says: connected and short after connection: disconnected
If connection to car BT HF is disconnected connection of dongle lasts and there is no problem
It can be problem of BT stack of win10, but I wrote it here to be sure you know it.
feel free to close this issue :)

**Comment by VaijanathA** [comment]
@PiDiBi The UWP Bluetooth connectivity screen shows disconnected very frequently. Did you face any dialog that complained about unable to connect to bluetooth device after you paired ?  I have seen this issue multiple times when the Bluetooth device says paired but not connected and works fine when the app tries to read information from the OBD device. Please reopen this issue if the connectivity fails and the app does not work for you. Thanks for reporting this issue.

**Comment by PiDiBi** [comment]
yes UWP app shows: unable to connect to OBD, Retry/Simulate
after switching BT HF off it works
