### ISSUE TITLE
obd driver error crashes

### ISSUE THREAD

**Issue by PiDiBi** [Azure-Samples/MyDriving#511]
Hi, i don't know if are you interested, but here are two crashes from hockey app

`
Incident Identifier: a1ba8fa1-2ce5-4d1a-a4cf-4cf7ad3646ef
CrashReporter Key:   X02+I1MNFw5O3qj7zPSPwRi7CycAXsRhgYse7emqUEI=
Hardware Model:      RM-1116_15169
Process:         N/A [0]
Path:            N/A
Identifier:      MyDriving.UWP
Version:         1.0.4.0
Parent Process:  N/A [0]

Date/Time:       2016-04-21T07:38:44.9600715Z
OS Version:      Windows 10.0.14327.1000
Report Version:  104

Exception Type:  System.InvalidOperationException
Exception Codes: N/A at N/A
Crashed Thread:  7

Application Specific Information:
A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)

Exception Stack:
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
ObdLibUWP.ObdWrapper.<PollObd>d__13.MoveNext()
`

and

`
ncident Identifier: 6dea4e89-2e79-495e-9416-815307b9d6e6
CrashReporter Key:   X02+I1MNFw5O3qj7zPSPwRi7CycAXsRhgYse7emqUEI=
Hardware Model:      RM-1116_15169
Process:         N/A [0]
Path:            N/A
Identifier:      MyDriving.UWP
Version:         1.0.4.0
Parent Process:  N/A [0]

Date/Time:       2016-04-21T08:22:07.2331960Z
OS Version:      Windows 10.0.14327.1000
Report Version:  104

Exception Type:  System.InvalidOperationException
Exception Codes: N/A at N/A
Crashed Thread:  30

Application Specific Information:
A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)

Exception Stack:
Windows.Networking.Sockets.StreamSocket.CancelIOAsync()
ObdLibUWP.ObdWrapper.<PollObd>d__13.MoveNext()
`

**Comment by xiangyan99** [comment]
Hi PiDiBi

Do you have a repro on these issues? We saw some issues with similar call stacks and we are working on them. We are not sure if yours are same as those or not.

**Comment by PiDiBi** [comment]
no, but after next crash I will try to remember what I did before

**Comment by xiangyan99** [comment]
Thank you. I checked in a fix for such crash and will close this issue. Please update to the latest version and open new issues if you see it again.
