### ISSUE TITLE
UI problem - starting trip

### ISSUE THREAD

**Issue by PiDiBi** [Azure-Samples/MyDriving#512]
UWP app
1. OBD disconected, hit start button
2. app asks: Simulated or retry? 
3. switch to BT settings, connect OBD
4. switch to app
result: dialog dismissed and trip is started with with OBD simulated
expected: dialog is still there and I can hit retry button

**Comment by harikm86** [comment]
Thanks for reporting this. We are focusing on unblocking customers and fixing key reliability issues. Since there is an easy workaround (restart the app). We will be closing this issue
