### ISSUE TITLE
ML cannot be deployed 

### ISSUE THREAD

**Issue by NoirRyu** [Azure-Samples/MyDriving#533]
I've tried to deploy solution in "WestUS" 
as demonstrated in the script, I generated .cer file and uploaded that into my Azure portal. 

When I encountered the prompted message, I enter the uploaded .cer files thumbprint then pushed the enter button. After that, many error messages were generated as below. 
I've tried this process several times but same. Any one knows this issue? 

Please provide the thumbprint of your Azure management certificate. Press [Enter] directly to sign in using AAD.: (.cer file's thumbprint uploaded in my azure portal ) 

error message : 
Invoke-RestMethod : ForbiddenErrorThe server failed to authenticate the request. Verify that the certificate is valid and is
associated with this subscription.
At C:\Users\rjhch\Downloads\MyDriving\scripts\PowerShell\scripts\copyMLExperiment.ps1:35 char:15
+ ...      $res = Invoke-RestMethod -Uri $URI -Method $method -Headers $hea ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : ForbiddenErrorThe server failed to authenticate the request. Verify that the certificate is valid and is
associated with this subscription.
At C:\Users\rjhch\Downloads\MyDriving\scripts\PowerShell\scripts\copyMLExperiment.ps1:55 char:15
+ ...      $res = Invoke-RestMethod -Uri $URI -Method $method -Headers $hea ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : ForbiddenErrorThe server failed to authenticate the request. Verify that the certificate is valid and is
associated with this subscription.

**Comment by PiDiBi** [comment]
Hi, I had same problem: https://github.com/Azure-Samples/MyDriving/issues/506
this worked for me:

makecert -sky exchange -r -n "CN=db1" -pe -a sha1 -len 2048 -ss My db1.cer
go to https://manage.windowsazure.com/ - Settings - Management Certificates and upload certificate
copy thumbprint and use for importing ML experiments

another solutions:
try Windows PowerShell ISE to debug powershells script for deploy
use this script to deploy it manualy:

[string]$thumbprint = "here put your thumbprint"
.\copyMLExperiment.ps1 "your azure subscription id" "resourcegroupname" "southcentralus" "youremail" "storagename" "storagekey" "https://storage.azureml.net/directories/2e55da807f4a4273bfa99852d3d6e304/items" "MyDriving" "https://storage.azureml.net/directories/a9fb6aeb3a164eedaaa28da34f02c3b0/items"  "MyDriving [Predictive Exp.]" $thumbprint

**Comment by NoirRyu** [comment]
Thanks for replay, I'll do that way! 
Have a good day.
