### ISSUE TITLE
test user for mydriving

### ISSUE THREAD

**Issue by Majda-Wazzan** [Azure-Samples/MyDriving#536]
Hi
I need to test mydriving app on my lenovo android tab 
How can I test it.

I got hocky app account and i go to my account but i didn't got how to add mydriving app and ltest it

Notice i didn't attend build.
Thanks

**Comment by harikm86** [comment]
Please check out the directions here https://azure.microsoft.com/en-us/documentation/articles/iot-solution-get-started/
