### ISSUE TITLE
ui tests failing in xamarin test cloud

### ISSUE THREAD

**Issue by PiDiBi** [Azure-Samples/MyDriving#539]
it's not able to skip splash screen

**Comment by jamesmontemagno** [comment]
Did you set the deployment to UITest as the build, not debug or release. This build config setups special things for XTC

**Comment by PiDiBi** [comment]
this is my setup
http://screencast.com/t/hz6Us9Kc1Ar
is it wrong?
thx

**Comment by jamesmontemagno** [comment]
Sorry for the delay on this. basically I have multiple builds:
![image](https://cloud.githubusercontent.com/assets/1676321/16165803/00423206-349b-11e6-80e3-7c035d9ed9ce.png)

ONLY feature and regression actually push to the test cloud and the main master always builds the release build. 

For the Feature/Regression I have XTC set as the build configuration:
![image](https://cloud.githubusercontent.com/assets/1676321/16165826/209bc300-349b-11e6-8fac-8df82a53ddb5.png)
