### ISSUE TITLE
Certificate .pfx not found

### ISSUE THREAD

**Issue by dstrebel** [Azure-Samples/MyDriving#540]
When building the the MyDriving app (Mydriving.UWP) I get a cannot find certificate mydriving.pfx error. This could just be a misstep on my part.

**Comment by alinapopa** [comment]
This is a warning and it's expected, there is no pfx file. You may have the project set to treat warnings as errors.

**Comment by dstrebel** [comment]
It's when create the app package bundle. Everything is set to not treat warnings as errors.

**Comment by alinapopa** [comment]
The issue opened says "When building the the MyDriving app ...". Missing pfx file won't affect building and running the app.
If you need a certificate you can generate one http://stackoverflow.com/questions/35475059/how-to-generate-a-new-pfx-file-after-being-lost-from-source-control 
1.In Visual Studio, from Solution Explorer, open Package.appxmanifest
2.In the App Manifest Designer, choose the Packaging tab, and then choose the Choose Certificate button.
3.In the Choose Certificate dialog box, expand the Configure Certificate list, and then choose Create test certificate.
4.In the Create test certificate dialog box, click the OK button.
