### ISSUE TITLE
Reference implementation of Azure Xamarin.iOS data connection?

### ISSUE THREAD

**Issue by mikakouvo** [Azure-Samples/MyDriving#543]
Hi!

I'm real rookie on this (Azure, VS, SQL...you name it) and would need an advice. I tried to follow Azure -> Mobile App -> Settings -> Quick Start -> Xamarin.iOS instructions (below) for data connection, but the last part was way too heavy for me...would someone share a reference implementation I could get back on track? 

Cheers!
Mika

If using Visual Studio, right-click your project and select "Manage NuGet Packages" search for the Microsoft.Azure.Mobile.Client package, and click "Install."
In your main Activity file, add a "using Microsoft.WindowsAzure.MobileServices;" statement. Then copy and paste in the following code:

public static MobileServiceClient MobileService = 
    new MobileServiceClient(
    "https://***.azurewebsites.net"
);

Add a sample TodoItem class to your project:

public class TodoItem
{
    public string Id { get; set; }
    public string Text { get; set; }
}

Finally, use the client library to start working with the TodoItem table in your server project. In your project, find a place where this interaction would make sense and add the following:

CurrentPlatform.Init();
TodoItem item = new TodoItem { Text = "Awesome item" };
await MobileService.GetTable<TodoItem>().InsertAsync(item);

**Comment by PiDiBi** [comment]
Hi you can start here with learning path: https://azure.microsoft.com/en-us/documentation/learning-paths/appservice-mobileapps/
We cannot support creating mobile apps from scratch here.
Thx for understanding

**Comment by mikakouvo** [comment]
Hi!

Understand totally. I was about to delete my question after realizing it's off topic, but forgot to do so.

I'll continue my journey on learning curve...thank's for the link!

Mika
