### ISSUE TITLE
Error with deploy.ps1 -> SQLSprocCleanupPipeline' failed with message 'The resource operation completed with terminal provisioning state 'Failed'.'

### ISSUE THREAD

**Issue by PeterSterk** [Azure-Samples/MyDriving#544]
During running deploy.ps1, I end up with the following error message:

New-AzureRmResourceGroupDeployment : 10:18:16 - Resource Microsoft.DataFactory/datafactories/datapipelines 'mydriving-dfbjokizo7zoahc/SQLSprocCleanupPipeline' failed with message 'The resource operation completed with terminal p
rovisioning state 'Failed'.'
At C:\Data\MyDriving-master\scripts\PowerShell\deploy.ps1:144 char:16
+ ... ployment2 = New-AzureRmResourceGroupDeployment -Name "$DeploymentName ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

Not sure what to do next?

Thanks, Peter

**Comment by PiDiBi** [comment]
do you have src\HDInsight\hivescripts\*.hql scripts at correct destination?
as first step of deploy they are uploaded to storage account
you must have same value of baseName property in scenario_complete.json and prerequisites.json if you changed it

**Comment by PeterSterk** [comment]
Yes, I have 6 items in that folder and they upload successfully at the beginning. I haven't changed the baseName property in either files (keeping all defaults). The thing is, 2-3 weeks ago I was able to successfully deploy using the same scripts...

**Comment by PiDiBi** [comment]
try pls this: find Data factory in azure portal and look for this pipeline - Pipelines Tile, there could be some error visible

I will try add later VS2015 solution to project with DataFactory as project to easily edit and publish it

**Comment by PiDiBi** [comment]
reproduced, will try to fix it

**Comment by PeterSterk** [comment]
Great, looking forward to that fix. Thanks in advance!

**Comment by PiDiBi** [comment]
it will take some time (testing takes time), if you wanna deploy without HDInsight, delete it form json script - try to find /* Create Data Factory */

**Comment by PeterSterk** [comment]
I have seen your comment in issue #525, not sure where I can change that and to what value?

**Comment by PiDiBi** [comment]
it's old comment/issue before I joined team, I will clean old issues
it's fixed in \src\DataFactory\ - you need add FinalTempDataSet-Sql dataset and link it to this dataset
but it's not fixed in ARM json file
I'm working on it

**Comment by PiDiBi** [comment]
fixed deployment of Data Facatory (fixed and tested deployment not if DF is working)
another issues for DF exists - will work on it later
