### ISSUE TITLE
Wont install on Windows 10 phone

### ISSUE THREAD

**Issue by dstrebel** [Azure-Samples/MyDriving#545]
The app installed fine on Windows 10 laptop, but not on Windows 10 phone. When I hit the install button on Windows 10 phone looks like it's going to install, but never does. No errors, no nothing.

**Comment by PiDiBi** [comment]
Hi, what do you mean with "install button"?
In Visual Studio, you need to change platform to ARM http://screencast.com/t/pAjQsK3ns
