### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by dstrebel** [Azure-Samples/MyDriving#552]
Get the following error when running the deploy.ps1. In the Azure portal it shows a 404 cant find linked service.

New-AzureRmResourceGroupDeployment : 11:37:34 AM - Resource Microsoft.DataFactory/datafactories/datasets 'mydrivingds-dfgjdbjjrqgfmo6/FinalTempDataSet-Sql' failed with message 'Linked service AzureSqlLinkedService not found.'
At C:\git\MyDriving\scripts\PowerShell\deploy.ps1:147 char:16
+ ... ployment2 = New-AzureRmResourceGroupDeployment -Name "$DeploymentName ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

**Comment by PiDiBi** [comment]
please paste whole script, but this is probably because first part of deployment didn't upload *.hql scripts to storage 
and "side" question, did you changed baseName variable in json files? must be same in prerequisites.json and scenario_complete.json

**Comment by IsmaelKP** [comment]
Same exact error on Deployment I used the original Deploy1.ps1 script

my whole script is as it 

[Output.txt](https://github.com/Azure-Samples/MyDriving/files/328077/Output.txt)

**Comment by PiDiBi** [comment]
you are using old version of deploy script and json files
in new version is in output warning about SQL password strength
please update your code from our repo

**Comment by IsmaelKP** [comment]
Hi I made sure to use the deploy.ps1 version you uploaded 9 days ago and also the new vesion of ARM templates. I did deploy succesfully thank you.

**Comment by PiDiBi** [comment]
you are welcome
