### ISSUE TITLE
publish mobile app service issue

### ISSUE THREAD

**Issue by ludsh2000** [Azure-Samples/MyDriving#553]
When I published the mobile app service, it will cause VS2015 to stop working and restart.
I tried it with other computer that installed vs2015, with the same issue.
but When I open the mobile app site 
https://mydriving-rqzoe4ixlxqay.azurewebsites.net/  it showed that it's up and running.

What's more, when I debug the mobile app, I found many 404 error for /tables/POI/?....  but It's okay for /tables/Trip and others tables.

**Comment by PiDiBi** [comment]
your site shows me error, pls try tu use some VM with VS2015 prepared in azure market place to publish it, or build it and publish via FTP
