### ISSUE TITLE
Machine Learning Contains no Workplace deploy1 fails

### ISSUE THREAD

**Issue by Netchicken** [Azure-Samples/MyDriving#554]
Following the setup instructions, I added the Account Name and the Account Key. However there is no path to Container, the outdated pic shows truncated tripdata/tables/mlinput/*(  

Here is a screenshot of what it should look like
![pathtocontainermanual](https://cloud.githubusercontent.com/assets/14264079/16212776/33072d1c-379e-11e6-95d8-fe530fb10be8.PNG)

Here is what I get. Note the empty field
![pathtocontainer](https://cloud.githubusercontent.com/assets/14264079/16212761/16e437ec-379e-11e6-8723-d333ad8e5312.PNG)
om/SIcP2tC

**Comment by PiDiBi** [comment]
did you import ML project or do you try to setup your own? (better to import it, there is no setup guide for ML experiment that covers whole setup)
paste tripdata/tables/mlinput/* in empty field, it's the path to data within storage

**Comment by Netchicken** [comment]
Thanks for that, tripdata/tables/mlinput/*  returns a 404 error.

The remote server returned an error: (404) Not Found."}}}}}Error: Sorry, it seems that you have encountered an internal system error. Please contact amlforum@microsoft.com with the full URL in the browser and the time you experienced the failure.

Web Service Parameters
Path to container, directory or blob



In the screenshot there seems to be an open bracket after the *

I am just stepping through the exercise, not creating my own.

**Comment by Netchicken** [comment]
I think I have an idea. The locations are different for the workspace and the storage, are they the same acc?
![location](https://cloud.githubusercontent.com/assets/14264079/16247658/e920734a-385e-11e6-8e55-0faf9089cdbf.PNG)

**Comment by Netchicken** [comment]
I have deleted and rerun the scripts, here is the problem area. The instructions say...
7.	Now, go to the Azure classic portal, select the Machine Learning service and then the mydriving workspace. 
8.	Open the workspace by selecting Sign-in to ML Studio.

However there isn't any workspace shown, just the opportunity to create a new one. In the last build I did that, hoping voodoo would join it to our existing one, but it didn't.
![nomachinelearningworkspace](https://cloud.githubusercontent.com/assets/14264079/16251055/fac08d02-3876-11e6-97a5-5ed53f799f57.PNG)

**Comment by Netchicken** [comment]
The issue might be this 

Before the Machine Learning workspaces are imported, you'll be asked to provide the thumbprint of your Azure management certificate. Paste in the thumbprint and press [Enter] to continue. If you press [Enter] directly, the script will attempt to sign in using AAD. You can use the latter option if you are the owner of your subscription.

When running the script I didn't get this instruction to provide a thumbprint, Is there another way to activate it now I am 1/2 way through?

**Comment by VaijanathB** [comment]
@Netchicken Did you follow all the manual setup instructions from https://github.com/Azure-Samples/MyDriving/tree/master/scripts ? These steps should be followed after you run the power shell script. 

And for the ML import please use the thumbprint method as UserName/Password has not been working reliably for many users.

**Comment by Netchicken** [comment]
Well I created a thumbprint and added it to the deploy1.ps now I get errors that are simlar to others at

At C:\Users\Gary\Desktop\MyDriving2\MyDriving\scripts\PowerShell\deploy.ps1:147 char:16
+ ... ployment2 = New-AzureRmResourceGroupDeployment -Name "$DeploymentName ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

[output.txt](https://github.com/Azure-Samples/MyDriving/files/329033/output.txt)

With this Project MS marketing have made a wonderful site saying how great it is and easy to install, yet all I have seen so far is what a Headache Azure is to set up. Its a pity I have a class of students wanting to work on this project. We are all stopped by the Azure issues for the last 3 days.

**Comment by harikm86** [comment]
Did you try this workaround out? https://github.com/Azure-Samples/MyDriving/issues/506

**Comment by Netchicken** [comment]
Yep we created and uploaded the Management cert using that workaround and copied the thumbprint.

**Comment by PiDiBi** [comment]
at the beginning you have this error:
Cannot find path 'C:\Users\ARM\scenario_complete.json' because it does not exist.
could you verify that you checked out whole project?

**Comment by Netchicken** [comment]
You were correct, in a move the ARM folders didn't go. 
I have redownloaded and run the script again. This time, for the first time, it asked for my thumbprint. However now I get a new error, or series of errors saying files are not digitally signed.

C:\Users\Gary\Desktop\MyDriving3\MyDriving\scripts\PowerShell\scripts\setupStorage.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running 
scripts and setting execution policy, see about_Execution




[output.txt](https://github.com/Azure-Samples/MyDriving/files/331028/output.txt)
_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.

**Comment by Netchicken** [comment]
Was not meant to be closed! My mistake!

**Comment by Netchicken** [comment]
OK fixed the permissions thing, now I get this, which is insane as its there and unchanged by me. Now at day 4 of trying to get this running. A lesser man would have given up by now :-)

Uploading hive scripts...
. : The term '.\scripts\Copy-ArtifactsToBlobStorage.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At C:\Users\Gary\Desktop\MyDriving3\MyDriving\scripts\PowerShell\deploy.ps1:125 char:3
+ . .\scripts\Copy-ArtifactsToBlobStorage.ps1 -StorageAccountName $depl ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\scripts\Copy-...BlobStorage.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Netchicken** [comment]
How can I get an error like this? It creates a file, then can't find it again. 
![anothererror](https://cloud.githubusercontent.com/assets/14264079/16328197/c7b758d0-3a2b-11e6-8476-50ca296f7bb2.png)

**Comment by Netchicken** [comment]
I reinstalled the project and ran it again finally getting over the Machine Language issue.
