### ISSUE TITLE
I have similar issues as one that was apparently fixed a few days ago

### ISSUE THREAD

**Issue by arturoqu** [Azure-Samples/MyDriving#556]
I have cloned the NEWEST depo (today at 2PM EST) locally via git, 

I have ran the deploy script, without making any changes to any file whatsoever, and using EASTUS as the target region, but I get the same error as some others had gotten, and apparently this was fixed.

I am also using strong passwords for when prompted to enter them.

We are using development boxes with latest version of VS2015 UP2, Azure PowerShell updated today JUN 27.

This must be something very obvious, but we are still not able to deploy this. Although we were able to deploy a few weeks ago, back in May 5th

Any help is appreciated

Thanks.

New-AzureRmResourceGroupDeployment : 3:00:10 PM - Resource Microsoft.DataFactory/datafactories/datasets 'mydriving-dfwso2h72e6lsn4/
  "message": "Linked service AzureSqlLinkedService not found.",
  "code": "LinkedServiceNotFound"
}'
At D:\MyDriving-master June 26 2016\scripts\PowerShell\deploy.ps1:147 char:16
+ ... ployment2 = New-AzureRmResourceGroupDeployment -Name "$DeploymentName ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by PiDiBi** [comment]
could you please paste whole output?

**Comment by arturoqu** [comment]
hello, thanks......attaching all output to this reply
[deploy output june 27 2016.txt](https://github.com/Azure-Samples/MyDriving/files/335698/deploy.output.june.27.2016.txt)

**Comment by zhimingyuan** [comment]
I confronted same issue!

**Comment by PiDiBi** [comment]
I see it, I will try to simulate it and fix it
problem is probably with missing dependency in ARM json script
AzureSqlLinkedService is required earlier than deployment of this part is finished

**Comment by arturoqu** [comment]
Thank you David, much appreciated....

**Comment by PiDiBi** [comment]
Could you pls help me with testing? I'm not able to simulate it but try to add this
```
,
			"[resourceId('Microsoft.DataFactory/datafactories/linkedServices', variables('dataFactoryName'), variables('sqlAnalyticsLinkedServiceName'))]"
```
at the end of line 1492
it's in part /* Dataset: FinalTempDataSet-Sql */ of file scripts\ARM\scenario_complete.json
and will look like this
```
"dependsOn": [
            "[resourceId('Microsoft.DataFactory/datafactories', variables('dataFactoryName'))]",
            "[resourceId('Microsoft.DataFactory/datafactories/linkedServices', variables('dataFactoryName'), variables('storageAsaLinkedServiceName'))]",
			"[resourceId('Microsoft.DataFactory/datafactories/linkedServices', variables('dataFactoryName'), variables('sqlAnalyticsLinkedServiceName'))]"
          ]
```

**Comment by arturoqu** [comment]
Thanks Dave.

OK, I have doen the above modification, added the one line to the scripts\ARM\scenario_complete.json file.

I now get the following error....

please take a look, it fails much earlier

Best regards,

ARTURO
[Mydriving error june 28 2016.txt](https://github.com/Azure-Samples/MyDriving/files/337654/Mydriving.error.june.28.2016.txt)

**Comment by PiDiBi** [comment]
probably some error during editing, I will try it to deploy and let you know

**Comment by PiDiBi** [comment]
fixed, tested - try it please from repo
[deployment_ok.txt](https://github.com/Azure-Samples/MyDriving/files/337730/deployment_ok.txt)

**Comment by arturoqu** [comment]
I used Powershell ISE to edit the file, all I did was to add the one line...hopefully I did not add any extra characters...;-)

		}            
          },
          "dependsOn": [
            "[resourceId('Microsoft.DataFactory/datafactories', variables('dataFactoryName'))]",
            "[resourceId('Microsoft.DataFactory/datafactories/linkedServices', variables('dataFactoryName'), variables('storageAsaLinkedServiceName'))]"
            "[resourceId('Microsoft.DataFactory/datafactories/linkedServices', variables('dataFactoryName'), variables('sqlAnalyticsLinkedServiceName'))]"
          ]
        },

**Comment by PiDiBi** [comment]
revert your changes and get last version from git, pls

**Comment by arturoqu** [comment]
OK, David, let me clone the repo again, and will let you know shortly.

So, I will clone the repo of which this dialog is part of...

Thanks and regards.

**Comment by PiDiBi** [comment]
or try to edit as you can see here 
https://github.com/Azure-Samples/MyDriving/commit/3564499b4dca826b7ad95af94f5e5036e8df964a
or get only this file from web here:
https://github.com/Azure-Samples/MyDriving/blob/master/scripts/ARM/scenario_complete.json

**Comment by arturoqu** [comment]
I cloned the entire repo, and it works very well now, thank you so much!!!

Best regards,

AQ

**Comment by PiDiBi** [comment]
you are welcome
