### ISSUE TITLE
Not enough cores to deploy

### ISSUE THREAD

**Issue by Schafschaf** [Azure-Samples/MyDriving#557]
Hello,

I tried to run the powershell script to set up the serices on azure but i get following error:

> New-AzureRmResourceGroupDeployment : 16:51:00 - Resource Microsoft.DataFactory/datafactories/linkedservices
> 'mydriving-blahblah/DailyComputeHDICluster' failed with message '{
>   "message": "Unable to create or update an on-demand HDInsight cluster with 24 cores for subscription
> [subscription id]. The Azure Data Factory quota for on-demand HDInsight cores for this subscription
> is 40, whereas 24 are currently reserved. If you would like to increase this quota, create a new Azure support request
> with issue type 'Quota' and quota type 'Data Factory'.",
>   "code": "MaxOnDemandHdiCoresReached"

How I can get this running? Do I have to pay for more cores? 

If the powershell script successed is the service finished and ready for the clients or is there something else to do?`

I appreciate any help, thank you :)

**Comment by PiDiBi** [comment]
You need to delete your unused VMs or request more cores allowed via support
https://azure.microsoft.com/cs-cz/documentation/articles/azure-subscription-service-limits/
