### ISSUE TITLE
connecting my Xamarin IoS app to MY azure backend

### ISSUE THREAD

**Issue by arturoqu** [Azure-Samples/MyDriving#558]
OK, so I deployed the back end using the scripts, thank you for that.

After obtaining my APPLE DEVELOPER account, I managed to compile and deploy the IOS application in XAMARIN to my IPHONE, the application works well, connects to my OBD device, and tracks my trips.

How do I connect my IOS application to my Azure backend?

What steps do I follow, where in the code do I enter the connection strings?

I have read all the GITHUB and Reference architecture docs, I can't find that info anywhere. In many places in the doc it says "go here for that info", but it is not there...

I undertand that I will have to re-compile my app with the hardocoded info about the connection to the back end, once I find out where to enter that info, but need guidance on this.

The more details, the better.

Thanks in advanced

AQ

**Comment by alinapopa** [comment]
DefaultMobileServiceUrl 
https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving.AzureClient/AzureClient.cs
DefaultHostName 
https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving.AzureClient/DeviceProvisionHandler.cs

**Comment by arturoqu** [comment]
Thanks you, I had found the first reference on my own,  and modified it, and it seemed to work...

I will follow your advice and modify both places.

Thank you so much.

BTW, you have al done  a superb job with this solution......iMHO the documentation should have this little tidbit reflected in it, also the piece about enabling the sign in options of the mobile app.

**Comment by arturoqu** [comment]
Alina, thank you. I have made the two changes you indicated above...I am making progress....

Now, the IoS device registers in the Azure IoT HUB, and I can see data in the Azure DB (dbo.trips table), but no messages make it to the Azure IoT HUB, 

Azure IoT hub indicates 1 device is registered (my IPhone) but no messages, is there anything else I need to change?

Thanks.

**Comment by alinapopa** [comment]
Try debugging the mobile app to see if data is uploaded successfully to IoT Hub. You can put breakpoints in the following places:

CurrentTripViewModel.cs   
obdDataProcessor.SendTripPointToIOTHub(CurrentTrip.Id, CurrentTrip.UserId, point);

OBDDataProcessor.cs

   try
            {
                await iotHub.SendEvent(packagedBlob);
            }
            catch (Exception e)
            {
                //An exception will be thrown if the data isn't received by the IOT Hub; store data in buffer and try again
                Logger.Instance.Track("Unable to send data to IOT Hub: " + e.Message);
                AddTripPointToBuffer(packagedBlob);
            }

**Comment by cateleu** [comment]
Hi - I replaced the strings as mentioned, but when I deployed and installed on Android device via HockeyApp, I got the following errors from adb log: 
( I had already creatde keystores and certificate followed from here)
https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/publishing_an_application/part_2_-_signing_the_android_application_package/

Any clues? Thanks

09-16 10:28:32.240: W/ActivityManager(755): No content provider found for permission revoke: file:///storage/emulated/0/Download/com.abb.mydriving.apk
09-16 10:28:32.240: I/PackageManager(755): Copying native libraries to /data/app-lib/vmdl1368652558
09-16 10:28:32.420: E/PackageParser(755): Package com.abb.mydriving has no certificates at entry AndroidManifest.xml; ignoring!
