### ISSUE TITLE
(Question) Can the trip run in background?

### ISSUE THREAD

**Issue by jakubsuchybio** [Azure-Samples/MyDriving#560]
Before purchasing OBD2 adapter, I just want to ask..
If I start the trip and go to homescreen of the phone, will the trip still run and will it be collecting data in background? I would like to use this with navigation at the same time. Is it possible? Thanks

**Comment by jakubsuchybio** [comment]
@jamesmontemagno Bump up for response. Please?

**Comment by harikmenon** [comment]
Yes it does collect it in the background.
