### ISSUE TITLE
Problem with Android when is compile 

### ISSUE THREAD

**Issue by genitalico** [Azure-Samples/MyDriving#561]
when I compile the solution for #android shows the following:
**System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.**

I have found the solution but it is strange,  I'm in mexico therefore I have my TimeZone with (UTC-06:00) Guadalajara, Mexico City, Monterrey but this is the cause of my problem, then I changed my time zone to (UTC-06:00) Central Time (US & Canada) now at the moment of compiling works correctly

**Comment by PiDiBi** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=42082
