### ISSUE TITLE
after deploying vinlookupApplication on servicefabric cluster, vinlookupservice state shows error

### ISSUE THREAD

**Issue by prbarl** [Azure-Samples/MyDriving#567]
management portal shows the following error: I see minreplicasize = 1 in Local1.Node.xml s.

Unhealthy Partition
Error Event: SourceId = 'System.FM', Property = 'State'
Partition is below target replica or instance count.

**Comment by PiDiBi** [comment]
Hi, what is your TargetReplicaSetSize?
Look at this link, I hope it helps you to troubleshoot SF, it's out of scope of this project
https://github.com/Azure/azure-content/blob/master/articles/service-fabric/service-fabric-understand-and-troubleshoot-with-system-health-reports.md
Thank you 
David
